### ISSUE TITLE
How to build a local deployment for ARM64?

### ISSUE THREAD

**Issue by reijin90** [golonzovsky/vacme-zurich-parser#2]
Hi!

Unfortunately, the golonzovsky/vacme-parser image is only provided for amd64/x86, so my ARM64 machine can't run it. I'm a bit confused how to get the Docker container for backend and frontend running. I built a new container, with the parser Dockerfile, but running the image in a container results in an error:
```
docker run --rm -it -e REGISTRATION_ID=XXXX -e REFRESH_TOKEN=eyJhbGciOiJI... golonzovsky/vacme-parser:arm64
Traceback (most recent call last):
  File "/app/main.py", line 202, in <module>
    config.load_incluster_config()
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 118, in load_incluster_config
    InClusterConfigLoader(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 204, in <module>
    config.load_kube_config()
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 792, in load_kube_config
    loader = _get_kube_config_loader(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 751, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

What am I missing here?

**Comment by golonzovsky** [comment]
feel free to reopen if you still have issues
